# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Gavin Shafer
# Username: shaferg
#
# Assignment: A03
# Purpose: make a cool picture while utilizing functions
# Google Doc Link: https://docs.google.com/document/d/1XMMkSFIAGl2GI8dkB-qkrbvDUzB189vSr6U2w9N6ils/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle

wn = turtle.Screen()    #creates window to my specifications
wn.bgcolor('blue')
wn.setworldcoordinates(-500,-500,500,500)


car = turtle.Turtle()   #creates turtle for "car"
car.color('red')

tires = turtle.Turtle() #creates turtle for "tires"
tires.color('black')

road = turtle.Turtle()  #creates turtle for "road"
road.color('gray')

grass = turtle.Turtle() #creates turtle for "grass"
grass.color('green')

sun = turtle.Turtle()     #creates turtle for "sun"
sun.color('orange')

house = turtle.Turtle()
house.color('brown')    #creates turtle for "house"

text = turtle.Turtle()  #allows me to write text

def makeroad():
    """"
    this function creates the road in my picture
    """
    road.hideturtle()           #makes turtle invisible (https://docs.python.org/3.0/library/turtle.html#turtle.screensize)
    road.pu()                   #creates road
    road.setpos(-500,-500)
    road.pd()
    road.begin_fill()
    for side in range(2):
        road.forward(1000)
        road.left(90)
        road.forward(200)
        road.left(90)
    road.end_fill()

def makecar():
    """"
    this function creates the car in my picture
    """
    car.hideturtle()
    car.pu()
    car.setpos(0, -300)
    car.pd()
    car.begin_fill()
    for side in range(2):
        car.forward(250)
        car.left(90)
        car.forward(100)
        car.left(90)
    car.end_fill()

def makegrass():
    """"
    this function makes the grass in my picture
    """
    grass.hideturtle()
    grass.pu()
    grass.setpos(-500, -300)
    grass.pd()
    grass.begin_fill()
    grass.forward(500)
    grass.left(90)
    grass.forward(100)
    grass.right(90)
    grass.forward(250)
    grass.right(90)
    grass.forward(100)
    grass.left(90)
    grass.forward(250)
    grass.left(90)
    grass.forward(250)
    grass.left(90)
    grass.forward(1000)
    grass.left(90)
    grass.forward(250)
    grass.end_fill()
    pass

def maketires():
    """
    this function makes the tires for the car
    """
    tires.hideturtle()
    tires.pu()
    tires.setpos(25, -325)
    tires.pd()
    tires.begin_fill()
    tires.circle(25)
    tires.end_fill()
    tires.pu()
    tires.forward(200)
    tires.pd()
    tires.begin_fill()
    tires.circle(25)
    tires.end_fill()

def makesun():
    """
    this function creates the sun
    """
    sun.hideturtle()
    sun.pu()
    sun.setpos(-500, 400)
    sun.pd()
    sun.begin_fill()
    sun.circle(100)
    sun.end_fill()

def makehouse():
    """
    this function creates the house
    """
    house.hideturtle()
    house.pu()
    house.setpos(-300,-100)
    house.pd()
    house.begin_fill()
    for side in range(2):
        house.forward(300)
        house.left(90)
        house.forward(400)
        house.left(90)
    house.end_fill()
def writetext():
    text.hideturtle()
    text.color('beige')
    text.penup()
    text.setpos(50, 350)
    text.pendown()
    text.write("A Summer's Afternoon", move=False, align='center', font=("Times New Roman", 30, ("italic", "normal")))

def main():
    """
    Docstring for main
    """
    makeroad()
    makecar()
    makegrass()
    maketires()
    makesun()
    makehouse()
    writetext()
    wn.exitonclick()
main()